### ISSUE TITLE
Update Bug...Error 1x6 at end of MacOS update

### ISSUE THREAD

**Issue by brianchin1000** [Ben216k/Patched-Sur#1]
Currently installed at 11.4 using v1.0.1....see preview for error at end of MacOS update using Post-Install-App.dmg. Error occurs at the very end of downloading macOS and never begins "preparing".

Thanks

![Screen Shot 2021-10-11 at 3 22 31 PM](https://user-images.githubusercontent.com/34774430/136844989-5051dce7-840d-4595-a48a-3c22093ef768.png)

**Comment by brianchin1000** [comment]
Tried rebooting several times. Ultimately re-downloaded full patched-sur.dmg and did full install with USB (despite updating from 11.4 to 11.6). Worked, but took a long time.

**Comment by ashiddokuru** [comment]
Another work around is using Patch Kext through the post install app from the original Patched Sur v1.0.0 via USB (offload). That's how I got it to work. Hope this helps too.

**Comment by brianchin1000** [comment]
Didn’t try that. Already installed and running great. If / when I have to update again I’ll post follow up
