### ISSUE TITLE
Transfer speed is painfully slow

### ISSUE THREAD

**Issue by Ali559** [Ben216k/Patched-Sur#11]
**Describe the bug**
I don't know why but when the app is copying the files, the speed is at 24KB/S, I have made the same USB bootable for a variety of systems and never have I ever observed such slow transfer speed.
Can someone help??
Screenshot of the process
![Screen Shot 2021-10-31 at 9 54 02 PM](https://user-images.githubusercontent.com/53957149/139597523-50ddbf2b-2f05-4540-b535-6ba8a923b406.png)

**Comment by Ben216k** [comment]
There's absolutely nothing that you can do about that, and it's not a patcher bug anyway so I'm going to close this issue.
