### ISSUE TITLE
[Failure]During the package verification

### ISSUE THREAD

**Issue by sepcnt** [Ben216k/Patched-Sur#15]
Device: 2012-Mid Macbook Pro
From: Catalina10.15.7
To: Big Sur 11.6.1

The installer said that package was broken.
PatchSur worked well without errors on 2012 MBP
The InstallAssistant.pkg's download link is extracted from Macbook Pro 2020, and has correct md5.

**Comment by Solomon-Wood** [comment]
### Try:
**1)** Using Patched Sur to download the installer package or,
**2)** * Or downloading the installer package from [this installer database](https://mrmacintosh.com/macos-big-sur-full-installer-database-download-directly-from-apple/), 
* Installing the package (double-click the file and run through the * Installer. This part will not install Big Sur, it will install the Installer App to your applications folder)
* And then running Patched Sur, then choose to select your own installer, and selecting `Install macOS Big Sur.app`.

**Comment by Ben216k** [comment]
You extracted the download link from a Mac? How the heck did you do that?

You ca do what solomonw1 said, but you can skip the second step and just select Browse then choose the InstallAssistant.pkg you downloaded.

*This issue will be closed in seven days if there is no reply.*
