### ISSUE TITLE
Patch Kexts not working

### ISSUE THREAD

**Issue by the-gael** [Ben216k/Patched-Sur#16]
**Describe the bug**
When I run Update Kexts via button in the Patcher v1.0.1 it fails

**To Reproduce**
1. Go to '.Patch Kexts..'
2. Click on 'Start Patch Kexts...'
3.Enter User Password....'

**Expected behavior**
I expected the kexts to be patched as I have done before

**Output from the patcher*
Error 1x127
Message: "/usr/local/lib/Patched-Sur-Patches/Scripts/PatchSystem.sh: line 66: /usr/local/lib/Patched-Sur-Patches/NeededPatches.sh: No such file or directory"
Output: "Checking environment...
[INFO] We're booted into full macOS.
[INFO] Using usr lib source.

Confirming patch location...
Set to detect patches, restarting PatchSystem with NeededPatches..."

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Big SUr 11.5
- Upgrading to: [e.g. Big Sur v11.6.1]
 - Mac Model: [2012 MacMini
 - Version [e.g. v1.0.1

**Additional context**
The scripts folder and the patches are present. I tried running one of the scripts using Scriptt editor but can't - suspect a permissions issue

If there are any red boxes, click on them to copy the logs.

**Comment by Ben216k** [comment]
This is a duplicate issue

**Comment by the-gael** [comment]
thank you just spotted the other one
