### ISSUE TITLE
This copy of the "InstallAssistant" application is damaged, and can‘t be used to install macOS.

### ISSUE THREAD

**Issue by wangmings** [Ben216k/Patched-Sur#20]
Problem Description:
    Use Patched-Sur to make macOS Big Sur 11.6 installation boot disk under macOS Catalina system,
    The production process went well without any errors, but the produced macOS Big Sur boot USB flash drive showed an error message during the installation: This copy of the "InstallAssistant" application is damaged, and can‘t be used to install macOS.

Description of the machine and software version used:
    Model: 2012 MacBook Pro 15-inch
    System: macOS Catalina 10.15.7
    Patched Sur version: v1.0.1
    MacOS Big Sur system download link:
        https://mrmacintosh.com/macos-big-sur-full-installer-database-download-directly-from-apple/
        http://swcdn.apple.com/content/downloads/43/03/002-23589-A_JLC10H5DJX/7qxktjph49leko1s3jwaqdlh2b3uzyrlfv/InstallAssistant.pkg

    Making tutorial reference:
        https://www.youtube.com/watch?v=q3J9kIDL0OI

Process of making U disk:
    Open the Patched Sur v1.0.1 software all the way to the next step, to the Set Update Track option: select Release and then go to the macOS Big Sur Version option: select Browse to enter the downloaded system image, and then by default, the next step is to complete the creation of a U disk

Reproduce the installation process and errors:
    After the Mac restarts, press the option key and select the EFI disk on the U disk and restart. After entering the macOS Big Sur installation disk to install, directly click the macOS Big Sur installation, and an error appears: This copy of the "InstallAssistant" application is damaged, and can't be used to install macOS.

**Comment by Nyxest** [comment]
Most likely it is an error derived from the official Apple installer, I tried to create a macOS Sierra installation disk with a .pkg and I got the same error.

**Comment by Ben216k** [comment]
This is something with Apple's weirdness that I can't do anything about.
