### ISSUE TITLE
Why? 

### ISSUE THREAD

**Issue by ernes1032** [Ben216k/Patched-Sur#21]
The patched sur doesn't work when i try to run updates
![Captura de pantalla 2021-11-17 a las 14 55 54](https://user-images.githubusercontent.com/85763641/142273268-5a9412aa-bf10-4a9c-9c97-df8f060c17ce.png)
Error code: The file “Developer.json” couldn’t be opened.

**Comment by Ben216k** [comment]
Get the latest version from the releases page, that should always be the first thing you do when you run into an issue. Also, I recommend enabling patcher update notifications, they don’t happen often but it ensures you're on the latest version.
