### ISSUE TITLE
Missing -no_compat_check boot arg

### ISSUE THREAD

**Issue by CarlosErnestoEM** [Ben216k/Patched-Sur#24]
Hello, I already have Big Sur(MBP Mid 2012 13 inch), but i reset de NVRAM because the caps lock light dont work
So, after doing it, every time I turn on my macbook PatchedSur opens with that message
![image](https://user-images.githubusercontent.com/6635725/143722880-d6aaa2da-3894-4c80-a034-115a1f54ff53.png)
How can it be fixed?

**Comment by Ben216k** [comment]
It helps to read the error.

**Comment by Ben216k** [comment]
Launch Patched Sur
