### ISSUE TITLE
prohibition sign screen 

### ISSUE THREAD

**Issue by benfrankie** [Ben216k/Patched-Sur#25]
HI, 
After clicking install option, it ends in a white screen with a prohibition sign. 
I think i followed the steps correctly and tried re-downloading, installing but no luck. 
I tried both "Release" and Beta and have 2012 mid macbook pro. 

any suggestions? 

thanks

**Comment by Blueysh** [comment]
Hello! Have you tried booting into "EFI Boot" before the "Install macOS Big Sur" volume? It's pretty much always a required step before upgrading. After that, your MacBook Pro should turn off, just power it back on and go into the boot selection screen, now you should be able to boot to "Install macOS Big Sur." Hope this helped!

**Comment by Ben216k** [comment]
What Blueysh said.

<This issue will be closed in seven days if there is no reply.>
