### ISSUE TITLE
Patched Sur 1.0.1 problem

### ISSUE THREAD

**Issue by martinpowi** [Ben216k/Patched-Sur#26]
Hi guys. I have an iMac late 2013 with patched Big Sur 11.6.2. When I open Patched Sur, I see a note at the bottom (screen attached). When I click it they suggest 2 ways of resolving the issue. Both of them DO NOT work for me. It is about the NVRAM.
Has anyone had that problem?

![Screenshot](https://user-images.githubusercontent.com/88580581/145098525-1a2cc324-91c9-4a84-9d34-9eccb27856f9.png)
![Screenshot 1](https://user-images.githubusercontent.com/88580581/145098563-eda638e5-15aa-4c66-8dfb-17b5c5b1632f.png)
![Screenshot 2](https://user-images.githubusercontent.com/88580581/145098590-72e61cea-6458-43d6-94d4-c32d2d260ea0.png)
![Screenshot 3](https://user-images.githubusercontent.com/88580581/145098605-bae4f4b3-1cda-4071-91ea-60dcd1edd5a5.png)

**Comment by mvmagalhaes** [comment]
![IMG_5261](https://user-images.githubusercontent.com/44643533/145236112-2c88393a-0891-455d-8764-8fa768100d28.JPG)
I followed these steps and it worked!

**Comment by martinpowi** [comment]
Thanks for your comment, but as I mentioned above, it strangely does not work on my iMac :(

**Comment by Ben216k** [comment]
Do you have OpenCore installed?

**Comment by martinpowi** [comment]
Yes, 0.3.2, GUI ant TUI.

**Comment by Ben216k** [comment]
Just delete Patched Sur then if you're not using it.

**Comment by Ben216k** [comment]
You do know that OCLP provides native updates right?

**Comment by martinpowi** [comment]
Yes, I know, but I would really like to sort out my issue. Is it doable?

**Comment by Ben216k** [comment]
Just delete the Patched Sur app, neither OC or PS supports double-patcher installs.
