### ISSUE TITLE
Error 1x127 and crashing in advanced configuration process

### ISSUE THREAD

**Issue by plattenschubse** [Ben216k/Patched-Sur#28]
When I patch kext I get this message. When I press "advanced configuration" the program crashes.
Do you have any ideas? Thank you!

Error 1x127
Message: "/usr/local/lib/Patched-Sur-Patches/Scripts/PatchSystem.sh: line 66: /usr/local/lib/Patched-Sur-Patches/NeededPatches.sh: No such file or directory"
Output: "Checking environment...
[INFO] We're booted into full macOS.
[INFO] Using usr lib source.

Confirming patch location...
Set to detect patches, restarting PatchSystem with NeededPatches..."

**Comment by Ben216k** [comment]
Duplicate issue
