### ISSUE TITLE
Patched Sur error 2x1

### ISSUE THREAD

**Issue by lilkem** [Ben216k/Patched-Sur#30]
Hello. I have a patched version of Catalina on my old Mac and I was trying to see if I can fix a certain error with patched Sur. For some reason when it's done copying the installer files, it gives me an error saying "Error 2x1: Installer not found." please help! I've been trying to have it successfully complete copying the files to the usb
(2 things. One, please don't say anything like "yeah I'm having this problem too I hope somebody can help," it annoys me. Two, I know my Mac is old. So don't remind me.) Thanks!

Upgrading from Catalina 10.15.7 to Big Sur 11.1
Model: 20" iMac Mid 2009
Version: 1.0.1

**Comment by Ben216k** [comment]
Well, your Mac is so... uhh... not young that Patched Sur doesn't support it to begin with (2012-2013 only).

So yeah, go try OCLP.
