### ISSUE TITLE
patch kexts fail,  macbook pro 15.6 early 2013

### ISSUE THREAD

**Issue by ZHENGX1N** [Ben216k/Patched-Sur#34]
patch kexts fail,  macbook pro 15.6 early 2013

Error 1x127
Message: "/usr/local/lib/Patched-Sur-Patches/Scripts/PatchSystem.sh: line 66: /usr/local/lib/Patched-Sur-Patches/NeededPatches.sh: No such file or directory"
Output: "Checking environment...
[INFO] We're booted into full macOS.
[INFO] Using usr lib source.

Confirming patch location...
Set to detect patches, restarting PatchSystem with NeededPatches..."

**Comment by Ben216k** [comment]
Duplicate
