### ISSUE TITLE
Cannot boot on the Install Big Sur (despite EFI boot activation)

### ISSUE THREAD

**Issue by valentinllpz** [Ben216k/Patched-Sur#35]
Hello!

First of all thanks for this amazing patcher. I have been using it for about a year without any kind of issue... until yesterday. 
For some reason my late 2012 iMac crashed and it won't restart. It's now stuck on a restart loop - apple logo shows up then after 40% of the bar loaded it crashes and repeats.

I have no clue why it suddenly stopped working. My guess is some kind of forced update (?) because I never updated it since I installed the patch back in February 2021.

Anyway, I tried to reinstall Big Sur patched by using your patcher (latest release) but now it gets stuck on the Apple logo before reaching the installer screen so I don't even have a chance to reinstall with Big Sur... Yes, I did the EFI boot step and it does not seem to be the issue since I don't have a forbidden logo. Soon after I select the install Big Sur, it starts loading and gets stuck.
I tried with every 11.6.X version available on your patcher, and on 2 different USB drives. 

Any idea about what may be happening?

Sadly the only way I have to get any logs would be to start in verbose mode, record it on my phone then send the video. If needed I can do that, let me know.

PS: I can start in single user mode, maybe I can do some stuff from there?

**Comment by cocotim** [comment]
Hi valentinllpz,

This problem as you describe it looks familiar to me, there was no way to get past the loading screen.

So the conclusion I had to draw was that the problem was with the hdd/ssd, so I'm not sure if this problem is due to the Big Sur update you describe.

But if this is also the case with you, you have probably lost all your files and you have to purchase a new SSD.

Maybe there is still another solution!
I wish you good luck

**Comment by valentinllpz** [comment]
Hi, 

Thank you for the answer.

It's been a (long) week and I guess have tried everything:
- booting up from my external bootable windows 10 or mac os mojave fails.
- I tried reinstalling Mojave / Catalina from an external hard drive and also from the internet recovery mode ; it always gets stuck at some point during the loading screen and I never managed to get to the recovery screen
- I bought a thunderbolt cable but the iMac hard drive does not seem to be detected by my Macbook pro

You are right, there might be a hardware problem with my hard drive. However, the fact that I am still able to detect it and run single user mode, internet recovery (download seems ok) + other startup options makes me think that the hardware is still ok, but some important data got corrupted. My last attempt will be to use a Finnix bootable drive and run from tests from there or erase it. 

I will keep you posted if I find a way to fix it, even though at this point I am starting to think it might be unrelated to this patcher.

**Comment by valentinllpz** [comment]
Hi,

A quick update on the situation: I burned Ubuntu to my flash drive and managed to boot from it with "Try Ubuntu" (only safe mode would boot though). From there I managed to mount my APFS Fusion Drive with apfs-fuse (big up to these guys for their work btw) and get my hand on my files.
I also checked the hard drive's health with several utilities and everything was fine. I erased the hard drive because I thought it might help but no, I still cannot get past the Apple logo loading screen for any kind of Mac OS install (from both USB and recovery mode).

This makes me think that the bootroom is corrupted, which is not a good news at all.
- Can you please let me know if this patcher modifies to the EFI bootroom? If it does, what is modified?
- Any tool you might advise I could boot from to flash the EFI bootroom back to a stable version? I cannot access to any kind of mac OS terminal, only linux if I boot from an USB drive.

Thank you.

**Comment by Ben216k** [comment]
That's an interesting predicament. 

To answer your questions:

- I do not mess with the anything other than files on your hard disk and two NVRAM values.
- As I said, I do not mess with this stuff, so I have no idea.
