### ISSUE TITLE
patcher not working

### ISSUE THREAD

**Issue by trizzle23** [Ben216k/Patched-Sur#36]
after i download the patcher & its time to double click so it can be ran on my MacBook it says it can't be opened because apple cannot check for its malicious software.

**Comment by Blueysh** [comment]
All you need to do here is right click on the app instead of double clicking. Select _Open_ and then in the dialog that shows _Open_ again. That'll run Patched Sur.

**Comment by Ben216k** [comment]
Research before making an issue.
