### ISSUE TITLE
Error when downloading Patched Sur

### ISSUE THREAD

**Issue by aaroncox82** [Ben216k/Patched-Sur#37]
**Describe the bug**![Screenshot 2022-01-05 at 21 50 23](https://user-images.githubusercontent.com/97197409/148295959-bfd9071e-ea46-421f-8c4d-594d7a602078.png)Every time I try to download Patch Sur a error message comes up part way through the download.

**To Reproduce**

1. Download latest Release of Patched Sur from GitHub
2. Open DMG file.
3. Select through to Download the actual real and latest version.
4. Download runs but then errors part way through normally at about 800MB.

**Expected behavior**
To download and the follow through with the rest of the procedure as set out on GitHub

**Screenshots**
![Screenshot 2022-01-05 at 21 50 23](https://user-images.githubusercontent.com/97197409/148296010-81ec1bd8-2072-4754-be0f-2119cfe82ef3.png)

![Screenshot 2022-01-05 at 21 50 23](https://user-images.githubusercontent.com/97197409/148295959-bfd9071e-ea46-421f-8c4d-594d7a602078.png)**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by Ben216k** [comment]
There's an issue for that.

**Comment by aaroncox82** [comment]
Great so what do i need to do?

**Comment by Ben216k** [comment]
Search the issue list for Error 1x18 issue, and find a solution there.

**Comment by aaroncox82** [comment]
Star thank you
