### ISSUE TITLE
Nvram Error - I can't Enter to my user

### ISSUE THREAD

**Issue by fabianramosg** [Ben216k/Patched-Sur#38]
![IMG_20220111_194937](https://user-images.githubusercontent.com/58567791/149049524-d78f7175-d228-4055-8258-b02a0e7374e6.jpg)
Hi @Ben216k When I opened the big sur patch app, it appeared that I had an error in the nvram so I did this step as described in the image but when I restart the computer it does not let me log in to my user, I enter the password and it does not let me move on from there. What I can do? I want to recover the system with all my files, when I start recovery it only lets me go back to macosx lion and does not allow me to do anything else. please help me 😭 thanks!

**Comment by Ben216k** [comment]
The previous page told you to make an installer, which was is the best way for you to get into recovery (actual Big Sur recovery doesn't boot since you don't have a supported Mac, but the patched installer is pretty much the equivalent). Do you have a way to make a Patched Sur installer? (Any Catalina or later Mac can do it)

**Comment by fabianramosg** [comment]
@Ben216k in this moment I don't have another computer at hand on which I can do this I understand that I should reinstall the big sur patch so I would recover my files and the system, but is there any other alternative?

**Comment by Ben216k** [comment]
Try resetting the NVRAM.

**Comment by fabianramosg** [comment]
it doesn't work either 😞, it doesn't pass the user password. To create the bootable usb, it must necessarily be done from a computer that has catalina or later? or can I do it from a mojave team? In this case, what I would have to do to recover everything would be to install the system again from the bootable usb, right?

**Comment by fabianramosg** [comment]
@Ben216k it doesn't work either 😞, it doesn't pass the user password. To create the bootable usb, it must necessarily be done from a computer that has catalina or later? or can I do it from a mojave team? In this case, what I would have to do to recover everything would be to install the system again from the bootable usb, right?

**Comment by fabianramosg** [comment]
Hello @Ben216k , I did the installer again but the problem seems to be due to an encrypted disk, it does not detect the password that I had put in it and apparently it also changed the user's password, I know that it no longer depends on you but you know any option to decrypt This disc? 😭

**Comment by Ben216k** [comment]
Oh you have FileVault on? That's a huge problem, Patched Sur does not play well with FileVault. The way to get rid of it is to make a backup and wipe it, but if you can't get access to the system at all I'm not sure how you'd make a backup.

**Comment by fabianramosg** [comment]
I tried to recover files through EraseUs data recovery connecting it to another mac but when I try to recover them I cannot open them, they tell me that the files also become encrypted and cannot be opened for that reason, I do not know how I could decrypt the disk and to be able to enter, or at least retrieve the information correctly, I enter through Internet recovery but it does not allow me to use sudo commands. 😞

**Comment by progamer562** [comment]
Don’t you even know your FileVault password?

**Comment by Ben216k** [comment]
*Reading the compatibility screen in the patcher would have benefited both of you.*

**Comment by Ben216k** [comment]
You can't unencrypt a disk with FileVault and Patched Sur (like it says on the compatibility screen), so the only method of recovery would be a backup, but I don't think we can do that if you can't boot your Mac.
