### ISSUE TITLE
Macbook Air mid2012, can't download latest Release.

### ISSUE THREAD

**Issue by glengib** [Ben216k/Patched-Sur#39]
I'm running on a MacBook Air, 13", Mid2012 (Model A1466). On the initial installer, I could not download the 11.6.1 nor 11.6.2 MacOS. I was able to download the 11.6 only. After what appears to be a successful installation of BigSur (11.6), I tried to upgrade using the PatchSur. Again, not getting past the download screen. The "Downloading Patches" complete, then the "Downloading MacOS" fails with either 11.6.2 or 11.6.1. 11.6.1 fails almost immediately with below screen shot:
![image](https://user-images.githubusercontent.com/81494367/149206421-82a62873-fe03-40b6-b4df-c150b9ad088e.png)

11.6.2 downloads ~1GB before failing with:
![image](https://user-images.githubusercontent.com/81494367/149208268-96ec961a-4509-4db9-a532-20959d20036a.png)
Error Text:

Error 1x18
Message: "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.5G    0 2909k    0     0  3072k      0  1:05:51 --:--:--  1:05:51 3069k
  0 11.5G    0 7899k    0     0  4057k      0  0:49:52  0:00:01  0:49:51 4054k
  0 11.5G    0 12.8M    0     0  4450k      0  0:45:28  0:00:02  0:45:26 4449k
  0 11.5G    0 18.1M    0     0  4704k      0  0:43:00  0:00:03  0:42:57 4703k
  0 11.5G    0 23.3M    0     0  4842k      0  0:41:47  0:00:04  0:41:43 4841k
  0 11.5G    0 28.0M    0     0  4834k      0  0:41:51  0:00:05  0:41:46 5168k
  0 11.5G    0 33.3M    0     0  4919k      0  0:41:08  0:00:06  0:41:02 5254k
  0 11.5G    0 38.9M    0     0  5019k      0  0:40:19  0:00:07  0:40:12 5353k
  0 11.5G    0 44.7M    0     0  5117k      0  0:39:32  0:00:08  0:39:24 5443k
  0 11.5G    0 50.4M    0     0  5191k      0  0:38:59  0:00:09  0:38:50 5536k
  0 11.5G    0 56.3M    0     0  5270k      0  0:38:23  0:00:10  0:38:13 5788k
  0 11.5G    0 61.9M    0     0  5306k      0  0:38:08  0:00:11  0:37:57 5846k
  0 11.5G    0 67.1M    0     0  5313k      0  0:38:04  0:00:12  0:37:52 5782k
  0 11.5G    0 73.0M    0     0  5363k      0  0:37:43  0:00:13  0:37:30 5804k
  0 11.5G    0 79.2M    0     0  5428k      0  0:37:16  0:00:14  0:37:02 5900k
  0 11.5G    0 85.6M    0     0  5497k      0  0:36:48  0:00:15  0:36:33 5993k
  0 11.5G    0 91.6M    0     0  5535k      0  0:36:33  0:00:16  0:36:17 6081k
  0 11.5G    0 96.8M    0     0  5526k      0  0:36:37  0:00:17  0:36:20 6076k
  0 11.5G    0  102M    0     0  5550k      0  0:36:27  0:00:18  0:36:09 6073k
  0 11.5G    0  108M    0     0  5585k      0  0:36:13  0:00:19  0:35:54 6054k
  0 11.5G    0  114M    0     0  5602k      0  0:36:07  0:00:20  0:35:47 5937k
  1 11.5G    1  119M    0     0  5582k      0  0:36:14  0:00:21  0:35:53 5744k
  1 11.5G    1  125M    0     0  5595k      0  0:36:09  0:00:22  0:35:47 5846k
  1 11.5G    1  131M    0     0  5621k      0  0:35:59  0:00:23  0:35:36 5887k
  1 11.5G    1  137M    0     0  5628k      0  0:35:57  0:00:24  0:35:33 5798k
  1 11.5G    1  142M    0     0  5609k      0  0:36:04  0:00:25  0:35:39 5638k
  1 11.5G    1  147M    0     0  5603k      0  0:36:06  0:00:26  0:35:40 5692k
  1 11.5G    1  152M    0     0  5603k      0  0:36:06  0:00:27  0:35:39 5638k
  1 11.5G    1  157M    0     0  5585k      0  0:36:13  0:00:28  0:35:45 5414k
  1 11.5G    1  162M    0     0  5566k      0  0:36:21  0:00:29  0:35:52 5261k
  1 11.5G    1  168M    0     0  5566k      0  0:36:21  0:00:30  0:35:51 5341k
  1 11.5G    1  172M    0     0  5528k      0  0:36:36  0:00:31  0:36:05 5123k
  1 11.5G    1  176M    0     0  5484k      0  0:36:53  0:00:32  0:36:21 4816k
  1 11.5G    1  180M    0     0  5431k      0  0:37:15  0:00:33  0:36:42 4538k
  1 11.5G    1  183M    0     0  5383k      0  0:37:35  0:00:34  0:37:01 4288k
  1 11.5G    1  187M    0     0  5328k      0  0:37:58  0:00:35  0:37:23 3853k
  1 11.5G    1  190M    0     0  5285k      0  0:38:17  0:00:36  0:37:41 3738k
  1 11.5G    1  194M    0     0  5254k      0  0:38:30  0:00:37  0:37:53 3740k
  1 11.5G    1  198M    0     0  5229k      0  0:38:41  0:00:38  0:38:03 3860k
  1 11.5G    1  203M    0     0  5215k      0  0:38:48  0:00:39  0:38:09 4038k
  1 11.5G    1  207M    0     0  5192k      0  0:38:58  0:00:40  0:38:18 4221k
  1 11.5G    1  211M    0     0  5163k      0  0:39:11  0:00:41  0:38:30 4256k
  1 11.5G    1  214M    0     0  5123k      0  0:39:30  0:00:42  0:38:48 4127k
  1 11.5G    1  218M    0     0  5091k      0  0:39:44  0:00:43  0:39:01 4016k
  1 11.5G    1  222M    0     0  5070k      0  0:39:54  0:00:44  0:39:10 3908k
  1 11.5G    1  226M    0     0  5056k      0  0:40:01  0:00:45  0:39:16 3941k
  1 11.5G    1  231M    0     0  5050k      0  0:40:04  0:00:46  0:39:18 4102k
  1 11.5G    1  236M    0     0  5053k      0  0:40:02  0:00:47  0:39:15 4458k
  2 11.5G    2  241M    0     0  5061k      0  0:39:58  0:00:48  0:39:10 4794k
  2 11.5G    2  247M    0     0  5074k      0  0:39:52  0:00:49  0:39:03 5117k
  2 11.5G    2  253M    0     0  5094k      0  0:39:43  0:00:50  0:38:53 5440k
  2 11.5G    2  259M    0     0  5119k      0  0:39:31  0:00:51  0:38:40 5773k
  2 11.5G    2  266M    0     0  5151k      0  0:39:17  0:00:52  0:38:25 6087k
  2 11.5G    2  272M    0     0  5173k      0  0:39:06  0:00:53  0:38:13 6271k
  2 11.5G    2  278M    0     0  5186k      0  0:39:01  0:00:54  0:38:07 6301k
  2 11.5G    2  283M    0     0  5195k      0  0:38:57  0:00:55  0:38:02 6226k
  2 11.5G    2  289M    0     0  5210k      0  0:38:50  0:00:56  0:37:54 6156k
  2 11.5G    2  294M    0     0  5207k      0  0:38:51  0:00:57  0:37:54 5799k
  2 11.5G    2  299M    0     0  5203k      0  0:38:53  0:00:58  0:37:55 5532k
  2 11.5G    2  304M    0     0  5204k      0  0:38:52  0:00:59  0:37:53 5405k
  2 11.5G    2  310M    0     0  5210k      0  0:38:50  0:01:00  0:37:50 5379k
  2 11.5G    2  315M    0     0  5220k      0  0:38:45  0:01:01  0:37:44 5325k
  2 11.5G    2  321M    0     0  5234k      0  0:38:39  0:01:02  0:37:37 5545k
  2 11.5G    2  326M    0     0  5234k      0  0:38:39  0:01:03  0:37:36 5587k
  2 11.5G    2  331M    0     0  5233k      0  0:38:40  0:01:04  0:37:36 5573k
  2 11.5G    2  336M    0     0  5222k      0  0:38:45  0:01:05  0:37:40 5361k
  2 11.5G    2  341M    0     0  5216k      0  0:38:47  0:01:06  0:37:41 5171k
  2 11.5G    2  345M    0     0  5214k      0  0:38:48  0:01:07  0:37:41 4963k
  2 11.5G    2  351M    0     0  5216k      0  0:38:47  0:01:08  0:37:39 4992k
  3 11.5G    3  356M    0     0  5224k      0  0:38:44  0:01:09  0:37:35 5111k
  3 11.5G    3  362M    0     0  5236k      0  0:38:38  0:01:10  0:37:28 5432k
  3 11.5G    3  368M    0     0  5249k      0  0:38:32  0:01:11  0:37:21 5691k
  3 11.5G    3  373M    0     0  5248k      0  0:38:33  0:01:12  0:37:21 5712k
  3 11.5G    3  379M    0     0  5257k      0  0:38:29  0:01:13  0:37:16 5827k
  3 11.5G    3  385M    0     0  5262k      0  0:38:27  0:01:14  0:37:13 5792k
  3 11.5G    3  388M    0     0  5240k      0  0:38:37  0:01:15  0:37:22 5289k
  3 11.5G    3  392M    0     0  5221k      0  0:38:45  0:01:16  0:37:29 4816k
  3 11.5G    3  396M    0     0  5208k      0  0:38:51  0:01:17  0:37:34 4630k
  3 11.5G    3  400M    0     0  5199k      0  0:38:55  0:01:18  0:37:37 4336k
  3 11.5G    3  405M    0     0  5195k      0  0:38:57  0:01:19  0:37:38 4189k
  3 11.5G    3  409M    0     0  5183k      0  0:39:02  0:01:20  0:37:42 4317k
  3 11.5G    3  414M    0     0  5175k      0  0:39:06  0:01:21  0:37:45 4467k
  3 11.5G    3  419M    0     0  5173k      0  0:39:06  0:01:22  0:37:44 4622k
  3 11.5G    3  424M    0     0  5173k      0  0:39:07  0:01:23  0:37:44 4759k
  3 11.5G    3  429M    0     0  5173k      0  0:39:06  0:01:24  0:37:42 4832k
  3 11.5G    3  434M    0     0  5179k      0  0:39:04  0:01:25  0:37:39 5110k
  3 11.5G    3  440M    0     0  5187k      0  0:39:00  0:01:26  0:37:34 5385k
  3 11.5G    3  446M    0     0  5198k      0  0:38:55  0:01:27  0:37:28 5619k
  3 11.5G    3  451M    0     0  5200k      0  0:38:54  0:01:28  0:37:26 5666k
  3 11.5G    3  457M    0     0  5205k      0  0:38:52  0:01:29  0:37:23 5749k
  3 11.5G    3  463M    0     0  5214k      0  0:38:48  0:01:30  0:37:18 5830k
  3 11.5G    3  469M    0     0  5227k      0  0:38:42  0:01:31  0:37:11 5919k
  4 11.5G    4  475M    0     0  5239k      0  0:38:37  0:01:32  0:37:05 5955k
  4 11.5G    4  481M    0     0  5252k      0  0:38:31  0:01:33  0:36:58 6159k
  4 11.5G    4  487M    0     0  5262k      0  0:38:27  0:01:34  0:36:53 6285k
  4 11.5G    4  492M    0     0  5259k      0  0:38:28  0:01:35  0:36:53 6065k
  4 11.5G    4  497M    0     0  5249k      0  0:38:32  0:01:36  0:36:56 5661k
  4 11.5G    4  500M    0     0  5233k      0  0:38:40  0:01:37  0:37:03 5120k
  4 11.5G    4  504M    0     0  5218k      0  0:38:46  0:01:38  0:37:08 4589k
  4 11.5G    4  508M    0     0  5206k      0  0:38:51  0:01:39  0:37:12 4144k
  4 11.5G    4  512M    0     0  5199k      0  0:38:55  0:01:40  0:37:15 4056k
  4 11.5G    4  517M    0     0  5195k      0  0:38:56  0:01:41  0:37:15 4142k
  4 11.5G    4  522M    0     0  5196k      0  0:38:56  0:01:42  0:37:14 4464k
  4 11.5G    4  527M    0     0  5199k      0  0:38:55  0:01:43  0:37:12 4816k
  4 11.5G    4  533M    0     0  5207k      0  0:38:51  0:01:44  0:37:07 5213k
  4 11.5G    4  539M    0     0  5217k      0  0:38:46  0:01:45  0:37:01 5587k
  4 11.5G    4  546M    0     0  5230k      0  0:38:41  0:01:46  0:36:55 5951k
  4 11.5G    4  552M    0     0  5245k      0  0:38:34  0:01:47  0:36:47 6265k
  4 11.5G    4  559M    0     0  5256k      0  0:38:30  0:01:48  0:36:42 6441k
  4 11.5G    4  565M    0     0  5269k      0  0:38:24  0:01:49  0:36:35 6583k
  4 11.5G    4  572M    0     0  5285k      0  0:38:17  0:01:50  0:36:27 6709k
  4 11.5G    4  578M    0     0  5292k      0  0:38:14  0:01:51  0:36:23 6613k
  4 11.5G    4  584M    0     0  5300k      0  0:38:10  0:01:52  0:36:18 6495k
  4 11.5G    4  591M    0     0  5311k      0  0:38:05  0:01:53  0:36:12 6521k
  5 11.5G    5  597M    0     0  5322k      0  0:38:01  0:01:54  0:36:07 6480k
  5 11.5G    5  604M    0     0  5335k      0  0:37:55  0:01:55  0:36:00 6444k
  5 11.5G    5  610M    0     0  5349k      0  0:37:49  0:01:56  0:35:53 6610k
  5 11.5G    5  617M    0     0  5362k      0  0:37:44  0:01:57  0:35:47 6764k
  5 11.5G    5  624M    0     0  5375k      0  0:37:38  0:01:58  0:35:40 6828k
  5 11.5G    5  630M    0     0  5383k      0  0:37:35  0:01:59  0:35:36 6780k
  5 11.5G    5  636M    0     0  5392k      0  0:37:31  0:02:00  0:35:31 6724k
  5 11.5G    5  642M    0     0  5394k      0  0:37:30  0:02:01  0:35:29 6450k
  5 11.5G    5  647M    0     0  5390k      0  0:37:32  0:02:02  0:35:30 6044k
  5 11.5G    5  651M    0     0  5386k      0  0:37:34  0:02:03  0:35:31 5651k
  5 11.5G    5  656M    0     0  5381k      0  0:37:36  0:02:04  0:35:32 5353k
  5 11.5G    5  660M    0     0  5372k      0  0:37:40  0:02:05  0:35:35 4874k
  5 11.5G    5  665M    0     0  5367k      0  0:37:42  0:02:06  0:35:36 4714k
  5 11.5G    5  669M    0     0  5358k      0  0:37:46  0:02:07  0:35:39 4557k
  5 11.5G    5  673M    0     0  5347k      0  0:37:50  0:02:08  0:35:42 4387k
  5 11.5G    5  677M    0     0  5340k      0  0:37:53  0:02:09  0:35:44 4292k
  5 11.5G    5  682M    0     0  5334k      0  0:37:55  0:02:10  0:35:45 4397k
  5 11.5G    5  687M    0     0  5331k      0  0:37:57  0:02:11  0:35:46 4423k
  5 11.5G    5  692M    0     0  5332k      0  0:37:57  0:02:12  0:35:45 4666k
  5 11.5G    5  697M    0     0  5334k      0  0:37:55  0:02:13  0:35:42 5002k
  5 11.5G    5  703M    0     0  5339k      0  0:37:54  0:02:14  0:35:40 5318k
  5 11.5G    5  708M    0     0  5336k      0  0:37:55  0:02:15  0:35:40 5373k
  6 11.5G    6  713M    0     0  5338k      0  0:37:54  0:02:16  0:35:38 5523k
  6 11.5G    6  719M    0     0  5344k      0  0:37:51  0:02:17  0:35:34 5667k
  6 11.5G    6  725M    0     0  5348k      0  0:37:50  0:02:18  0:35:32 5699k
  6 11.5G    6  730M    0     0  5344k      0  0:37:51  0:02:19  0:35:32 5488k
  6 11.5G    6  735M    0     0  5343k      0  0:37:52  0:02:20  0:35:32 5532k
  6 11.5G    6  740M    0     0  5344k      0  0:37:52  0:02:21  0:35:31 5491k
  6 11.5G    6  746M    0     0  5347k      0  0:37:50  0:02:22  0:35:28 5437k
  6 11.5G    6  752M    0     0  5352k      0  0:37:48  0:02:23  0:35:25 5484k
  6 11.5G    6  758M    0     0  5360k      0  0:37:45  0:02:24  0:35:21 5801k
  6 11.5G    6  765M    0     0  5369k      0  0:37:41  0:02:25  0:35:16 6116k
  6 11.5G    6  771M    0     0  5374k      0  0:37:39  0:02:26  0:35:13 6242k
  6 11.5G    6  777M    0     0  5378k      0  0:37:37  0:02:27  0:35:10 6271k
  6 11.5G    6  781M    0     0  5373k      0  0:37:39  0:02:28  0:35:11 5959k
  6 11.5G    6  785M    0     0  5362k      0  0:37:44  0:02:29  0:35:15 5437k
  6 11.5G    6  789M    0     0  5354k      0  0:37:47  0:02:30  0:35:17 4915k
  6 11.5G    6  793M    0     0  5348k      0  0:37:50  0:02:31  0:35:19 4579k
  6 11.5G    6  798M    0     0  5345k      0  0:37:51  0:02:32  0:35:19 4356k
  6 11.5G    6  803M    0     0  5344k      0  0:37:51  0:02:33  0:35:18 4493k
  6 11.5G    6  808M    0     0  5344k      0  0:37:51  0:02:34  0:35:17 4783k
  6 11.5G    6  813M    0     0  5339k      0  0:37:54  0:02:35  0:35:19 4870k
  6 11.5G    6  818M    0     0  5337k      0  0:37:54  0:02:36  0:35:18 5018k
  6 11.5G    6  823M    0     0  5339k      0  0:37:54  0:02:37  0:35:17 5149k
  6 11.5G    6  828M    0     0  5338k      0  0:37:54  0:02:38  0:35:16 5155k
  7 11.5G    7  831M    0     0  5325k      0  0:38:00  0:02:39  0:35:21 4733k
  7 11.5G    7  835M    0     0  5313k      0  0:38:04  0:02:40  0:35:24 4523k
  7 11.5G    7  838M    0     0  5304k      0  0:38:08  0:02:41  0:35:27 4260k
  7 11.5G    7  843M    0     0  5297k      0  0:38:11  0:02:42  0:35:29 3994k
  7 11.5G    7  847M    0     0  5293k      0  0:38:13  0:02:43  0:35:30 3860k
  7 11.5G    7  851M    0     0  5285k      0  0:38:17  0:02:44  0:35:33 4004k
  7 11.5G    7  854M    0     0  5271k      0  0:38:23  0:02:45  0:35:38 3905k
  7 11.5G    7  857M    0     0  5258k      0  0:38:28  0:02:46  0:35:42 3770k
  7 11.5G    7  860M    0     0  5243k      0  0:38:35  0:02:47  0:35:48 3479k
  7 11.5G    7  863M    0     0  5231k      0  0:38:40  0:02:48  0:35:52 3195k
  7 11.5G    7  866M    0     0  5220k      0  0:38:45  0:02:49  0:35:56 3089k
  7 11.5G    7  870M    0     0  5211k      0  0:38:49  0:02:50  0:35:59 3234k
  7 11.5G    7  874M    0     0  5205k      0  0:38:52  0:02:51  0:36:01 3412k
  7 11.5G    7  878M    0     0  5200k      0  0:38:54  0:02:52  0:36:02 3761k
  7 11.5G    7  883M    0     0  5198k      0  0:38:55  0:02:53  0:36:02 4100k
  7 11.5G    7  887M    0     0  5193k      0  0:38:57  0:02:54  0:36:03 4291k
  7 11.5G    7  890M    0     0  5181k      0  0:39:03  0:02:55  0:36:08 4135k
  7 11.5G    7  893M    0     0  5170k      0  0:39:08  0:02:56  0:36:12 3997k
  7 11.5G    7  897M    0     0  5162k      0  0:39:11  0:02:57  0:36:14 3833k
  7 11.5G    7  901M    0     0  5156k      0  0:39:14  0:02:58  0:36:16 3665k
  7 11.5G    7  905M    0     0  5152k      0  0:39:16  0:02:59  0:36:17 3703k
  7 11.5G    7  910M    0     0  5150k      0  0:39:17  0:03:00  0:36:17 4071k
  7 11.5G    7  915M    0     0  5150k      0  0:39:17  0:03:01  0:36:16 4418k
  7 11.5G    7  919M    0     0  5145k      0  0:39:19  0:03:02  0:36:17 4532k
  7 11.5G    7  923M    0     0  5142k      0  0:39:20  0:03:03  0:36:17 4672k
  7 11.5G    7  928M    0     0  5140k      0  0:39:22  0:03:04  0:36:18 4705k
  7 11.5G    7  932M    0     0  5134k      0  0:39:24  0:03:05  0:36:19 4547k
  7 11.5G    7  936M    0     0  5129k      0  0:39:27  0:03:06  0:36:21 4369k
  7 11.5G    7  941M    0     0  5127k      0  0:39:28  0:03:07  0:36:21 4467k
  7 11.5G    7  945M    0     0  5126k      0  0:39:28  0:03:08  0:36:20 4515k
  8 11.5G    8  951M    0     0  5127k      0  0:39:27  0:03:09  0:36:18 4657k
  8 11.5G    8  956M    0     0  5131k      0  0:39:26  0:03:10  0:36:16 5011k
  8 11.5G    8  962M    0     0  5136k      0  0:39:24  0:03:11  0:36:13 5385k
  8 11.5G    8  968M    0     0  5142k      0  0:39:21  0:03:12  0:36:09 5712k
  8 11.5G    8  975M    0     0  5150k      0  0:39:17  0:03:13  0:36:04 6047k
  8 11.5G    8  981M    0     0  5155k      0  0:39:15  0:03:14  0:36:01 6214k
  8 11.5G    8  987M    0     0  5158k      0  0:39:13  0:03:15  0:35:58 6203k
  8 11.5G    8  993M    0     0  5164k      0  0:39:11  0:03:16  0:35:55 6248k
  8 11.5G    8  998M    0     0  5163k      0  0:39:11  0:03:17  0:35:54 5996k
  8 11.5G    8 1003M    0     0  5165k      0  0:39:10  0:03:18  0:35:52 5766k
  8 11.5G    8 1007M    0     0  5161k      0  0:39:12  0:03:19  0:35:53 5405k
  8 11.5G    8 1012M    0     0  5159k      0  0:39:13  0:03:20  0:35:53 5187k
  8 11.5G    8 1017M    0     0  5157k      0  0:39:14  0:03:21  0:35:53 4895k
  8 11.5G    8 1022M    0     0  5157k      0  0:39:14  0:03:22  0:35:52 4915k
  8 11.5G    8 1024M    0     0  5158k      0  0:39:13  0:03:23  0:35:50 4836k
curl: (18) transfer closed with 11359609468 bytes remaining to read"
Output: ""

So I'm running BigSur 11.6 but can't upgrade to latest. Not sure this is a bug or just an incompatibility with my MacBook Air.

Thanks for your efforts.

**Comment by Blueysh** [comment]
There have been other people with the same issue, it's just a curl error. You can try downloading it externally and then using that in the installer.

**Comment by Ben216k** [comment]
Duplicate Issue

**Comment by glengib** [comment]
Thanks. I assumed closed issues were included in latest releases. Since this is happening still, perhaps reference the issue in install instructions.
Thanks all for your efforts. My MacBook Air 13" Mid 2012 now runs BigSur 11.6.2. I can backup my IOS15 iPhone once again.
