### ISSUE TITLE
Je n'arrive pas à charger patched sur, erreur 404

### ISSUE THREAD

**Issue by Lecledo** [Ben216k/Patched-Sur#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by Ben216k** [comment]
Nothing of this issue was filled out, and a 404 error is a network error for an unknown url (none of which Patched Sur has had in the past 6 months), so I'm closing this.
