### ISSUE TITLE
Cant Download Image

### ISSUE THREAD

**Issue by malkavianleon** [Ben216k/Patched-Sur#45]
When I try to download the imagem I get the error:

Error 1x18
Message: "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.5G    0  351k    0     0   188k      0 17:54:42  0:00:01 17:54:41  188k
  0 11.5G    0 1950k    0     0   677k      0  4:58:53  0:00:02  4:58:51  676k
  0 11.5G    0 5148k    0     0  1023k      0  3:17:42  0:00:05  3:17:37 1023k
  0 11.5G    0 7355k    0     0  1255k      0  2:41:15  0:00:05  2:41:10 1254k
  0 11.5G    0 11.1M    0     0  1659k      0  2:01:56  0:00:06  2:01:50 1895k
  0 11.5G    0 16.2M    0     0  2108k      0  1:35:59  0:00:07  1:35:52 2703k
  0 11.5G    0 22.3M    0     0  2565k      0  1:18:53  0:00:08  1:18:45 3467k
  0 11.5G    0 28.7M    0     0  2979k      0  1:07:55  0:00:09  1:07:46 5006k
  0 11.5G    0 36.4M    0     0  3417k      0  0:59:13  0:00:10  0:59:03 5928k
  0 11.5G    0 42.1M    0     0  3611k      0  0:56:02  0:00:11  0:55:51 6228k
  0 11.5G    0 47.3M    0     0  3732k      0  0:54:13  0:00:12  0:54:01 6242k
  0 11.5G    0 52.1M    0     0  3853k      0  0:52:31  0:00:13  0:52:18 6178k
  0 11.5G    0 59.5M    0     0  4108k      0  0:49:16  0:00:14  0:49:02 6351k
  0 11.5G    0 65.5M    0     0  4237k      0  0:47:45  0:00:15  0:47:30 6046k
  0 11.5G    0 74.0M    0     0  4496k      0  0:45:00  0:00:16  0:44:44 6652k
  0 11.5G    0 80.1M    0     0  4596k      0  0:44:01  0:00:17  0:43:44 6897k
  0 11.5G    0 87.2M    0     0  4734k      0  0:42:44  0:00:18  0:42:26 7166k
  0 11.5G    0 94.2M    0     0  4851k      0  0:41:43  0:00:19  0:41:24 7040k
  0 11.5G    0  101M    0     0  4988k      0  0:40:34  0:00:20  0:40:14 7351k
  0 11.5G    0  109M    0     0  5127k      0  0:39:28  0:00:21  0:39:07 7263k
  0 11.5G    0  117M    0     0  5273k      0  0:38:22  0:00:22  0:38:00 7682k
  1 11.5G    1  126M    0     0  5439k      0  0:37:12  0:00:23  0:36:49 8107k
  1 11.5G    1  134M    0     0  5517k      0  0:36:40  0:00:24  0:36:16 8159k
  1 11.5G    1  138M    0     0  5486k      0  0:36:53  0:00:25  0:36:28 7547k
  1 11.5G    1  144M    0     0  5508k      0  0:36:44  0:00:26  0:36:18 7173k
  1 11.5G    1  150M    0     0  5545k      0  0:36:29  0:00:27  0:36:02 6796k
  1 11.5G    1  156M    0     0  5538k      0  0:36:32  0:00:28  0:36:04 6009k
  1 11.5G    1  162M    0     0  5568k      0  0:36:20  0:00:29  0:35:51 5821k
  1 11.5G    1  168M    0     0  5596k      0  0:36:09  0:00:30  0:35:39 6178k
  1 11.5G    1  175M    0     0  5631k      0  0:35:56  0:00:31  0:35:25 6287k
  1 11.5G    1  182M    0     0  5703k      0  0:35:29  0:00:32  0:34:57 6580k
  1 11.5G    1  190M    0     0  5774k      0  0:35:03  0:00:33  0:34:30 7137k
  1 11.5G    1  198M    0     0  5821k      0  0:34:46  0:00:34  0:34:12 7333k
  1 11.5G    1  206M    0     0  5888k      0  0:34:22  0:00:35  0:33:47 7694k
  1 11.5G    1  214M    0     0  5948k      0  0:34:01  0:00:36  0:33:25 7974k
  1 11.5G    1  221M    0     0  5990k      0  0:33:47  0:00:37  0:33:10 7875k
  1 11.5G    1  229M    0     0  6042k      0  0:33:29  0:00:38  0:32:51 7859k
  1 11.5G    1  235M    0     0  6048k      0  0:33:27  0:00:39  0:32:48 7632k
  2 11.5G    2  242M    0     0  6064k      0  0:33:22  0:00:40  0:32:42 7322k
  2 11.5G    2  250M    0     0  6118k      0  0:33:04  0:00:41  0:32:23 7368k
  2 11.5G    2  256M    0     0  6119k      0  0:33:04  0:00:42  0:32:22 7096k
  2 11.5G    2  264M    0     0  6168k      0  0:32:48  0:00:43  0:32:05 7146k
  2 11.5G    2  273M    0     0  6237k      0  0:32:26  0:00:44  0:31:42 7739k
  2 11.5G    2  281M    0     0  6279k      0  0:32:13  0:00:45  0:31:28 8037k
  2 11.5G    2  289M    0     0  6321k      0  0:32:01  0:00:46  0:31:15 8021k
  2 11.5G    2  297M    0     0  6375k      0  0:31:44  0:00:47  0:30:57 8564k
  2 11.5G    2  305M    0     0  6396k      0  0:31:38  0:00:48  0:30:50 8398k
  2 11.5G    2  313M    0     0  6433k      0  0:31:27  0:00:49  0:30:38 8199k
  2 11.5G    2  321M    0     0  6475k      0  0:31:15  0:00:50  0:30:25 8276k
  2 11.5G    2  329M    0     0  6510k      0  0:31:05  0:00:51  0:30:14 8283k
  2 11.5G    2  338M    0     0  6557k      0  0:30:51  0:00:52  0:29:59 8305k
  2 11.5G    2  345M    0     0  6575k      0  0:30:46  0:00:53  0:29:53 8316k
  2 11.5G    2  353M    0     0  6595k      0  0:30:41  0:00:54  0:29:47 8208k
  3 11.5G    3  361M    0     0  6629k      0  0:30:31  0:00:55  0:29:36 8198k
  3 11.5G    3  369M    0     0  6660k      0  0:30:23  0:00:56  0:29:27 8210k
  3 11.5G    3  378M    0     0  6693k      0  0:30:14  0:00:57  0:29:17 8128k
  3 11.5G    3  386M    0     0  6718k      0  0:30:07  0:00:58  0:29:09 8259k
  3 11.5G    3  393M    0     0  6726k      0  0:30:05  0:00:59  0:29:06 8160k
  3 11.5G    3  401M    0     0  6763k      0  0:29:55  0:01:00  0:28:55 8260k
  3 11.5G    3  410M    0     0  6801k      0  0:29:45  0:01:01  0:28:44 8408k
  3 11.5G    3  418M    0     0  6823k      0  0:29:39  0:01:02  0:28:37 8329k
  3 11.5G    3  427M    0     0  6855k      0  0:29:31  0:01:03  0:28:28 8464k
  3 11.5G    3  433M    0     0  6847k      0  0:29:33  0:01:04  0:28:29 8294k
  3 11.5G    3  442M    0     0  6874k      0  0:29:26  0:01:05  0:28:21 8216k
  3 11.5G    3  449M    0     0  6885k      0  0:29:23  0:01:06  0:28:17 7933k
  3 11.5G    3  457M    0     0  6901k      0  0:29:19  0:01:07  0:28:12 7878k
  3 11.5G    3  464M    0     0  6906k      0  0:29:18  0:01:08  0:28:10 7560k
  3 11.5G    3  473M    0     0  6935k      0  0:29:10  0:01:09  0:28:01 8086k
  4 11.5G    4  477M    0     0  6888k      0  0:29:22  0:01:10  0:28:12 7076k
  4 11.5G    4  478M    0     0  6791k      0  0:29:48  0:01:12  0:28:36 5606k
  4 11.5G    4  479M    0     0  6698k      0  0:30:12  0:01:13  0:28:59 4190k
  4 11.5G    4  479M    0     0  6648k      0  0:30:26  0:01:13  0:29:13 3125k
  4 11.5G    4  484M    0     0  6623k      0  0:30:33  0:01:14  0:29:19 2287k
  4 11.5G    4  488M    0     0  6587k      0  0:30:43  0:01:15  0:29:28 2279k
  4 11.5G    4  493M    0     0  6568k      0  0:30:48  0:01:16  0:29:32 3127k
  4 11.5G    4  498M    0     0  6550k      0  0:30:53  0:01:17  0:29:36 4138k
  4 11.5G    4  503M    0     0  6531k      0  0:30:59  0:01:18  0:29:41 4794k
  4 11.5G    4  507M    0     0  6507k      0  0:31:06  0:01:19  0:29:47 4761k
  4 11.5G    4  513M    0     0  6497k      0  0:31:08  0:01:20  0:29:48 5118k
  4 11.5G    4  518M    0     0  6482k      0  0:31:13  0:01:21  0:29:52 5149k
  4 11.5G    4  523M    0     0  6465k      0  0:31:18  0:01:22  0:29:56 5160k
  4 11.5G    4  528M    0     0  6453k      0  0:31:21  0:01:23  0:29:58 5222k
  4 11.5G    4  534M    0     0  6446k      0  0:31:23  0:01:24  0:29:59 5477k
  4 11.5G    4  539M    0     0  6437k      0  0:31:26  0:01:25  0:30:01 5468k
  4 11.5G    4  545M    0     0  6427k      0  0:31:29  0:01:26  0:30:03 5541k
  4 11.5G    4  550M    0     0  6413k      0  0:31:33  0:01:27  0:30:06 5539k
  4 11.5G    4  555M    0     0  6404k      0  0:31:36  0:01:28  0:30:08 5580k
  4 11.5G    4  561M    0     0  6401k      0  0:31:36  0:01:29  0:30:07 5634k
  4 11.5G    4  567M    0     0  6398k      0  0:31:37  0:01:30  0:30:07 5726k
  4 11.5G    4  573M    0     0  6394k      0  0:31:39  0:01:31  0:30:08 5812k
  4 11.5G    4  579M    0     0  6391k      0  0:31:40  0:01:32  0:30:08 6003k
  4 11.5G    4  586M    0     0  6395k      0  0:31:38  0:01:33  0:30:05 6237k
  5 11.5G    5  594M    0     0  6414k      0  0:31:33  0:01:34  0:29:59 6645k
  5 11.5G    5  601M    0     0  6424k      0  0:31:30  0:01:35  0:29:55 6891k
  5 11.5G    5  608M    0     0  6429k      0  0:31:28  0:01:36  0:29:52 7065k
  5 11.5G    5  615M    0     0  6439k      0  0:31:25  0:01:37  0:29:48 7327k
  5 11.5G    5  623M    0     0  6458k      0  0:31:20  0:01:38  0:29:42 7629k
  5 11.5G    5  631M    0     0  6474k      0  0:31:15  0:01:39  0:29:36 7606k
  5 11.5G    5  639M    0     0  6494k      0  0:31:09  0:01:40  0:29:29 7840k
  5 11.5G    5  647M    0     0  6512k      0  0:31:04  0:01:41  0:29:23 8128k
  5 11.5G    5  656M    0     0  6532k      0  0:30:58  0:01:42  0:29:16 8377k
  5 11.5G    5  664M    0     0  6549k      0  0:30:54  0:01:43  0:29:11 8347k
  5 11.5G    5  672M    0     0  6567k      0  0:30:49  0:01:44  0:29:05 8424k
  5 11.5G    5  680M    0     0  6579k      0  0:30:45  0:01:45  0:29:00 8299k
  5 11.5G    5  689M    0     0  6604k      0  0:30:38  0:01:46  0:28:52 8486k
  5 11.5G    5  697M    0     0  6622k      0  0:30:33  0:01:47  0:28:46 8475k
  5 11.5G    5  706M    0     0  6646k      0  0:30:27  0:01:48  0:28:39 8662k
  6 11.5G    6  714M    0     0  6661k      0  0:30:22  0:01:49  0:28:33 8637k
  6 11.5G    6  722M    0     0  6674k      0  0:30:19  0:01:50  0:28:29 8693k
  6 11.5G    6  731M    0     0  6697k      0  0:30:13  0:01:51  0:28:22 8669k
  6 11.5G    6  739M    0     0  6711k      0  0:30:09  0:01:52  0:28:17 8620k
  6 11.5G    6  747M    0     0  6727k      0  0:30:05  0:01:53  0:28:12 8494k
  6 11.5G    6  756M    0     0  6742k      0  0:30:01  0:01:54  0:28:07 8521k
  6 11.5G    6  764M    0     0  6757k      0  0:29:57  0:01:55  0:28:02 8579k
  6 11.5G    6  773M    0     0  6777k      0  0:29:51  0:01:56  0:27:55 8578k
  6 11.5G    6  781M    0     0  6786k      0  0:29:49  0:01:57  0:27:52 8473k
  6 11.5G    6  788M    0     0  6796k      0  0:29:46  0:01:58  0:27:48 8376k
  6 11.5G    6  797M    0     0  6812k      0  0:29:42  0:01:59  0:27:43 8420k
  6 11.5G    6  806M    0     0  6830k      0  0:29:37  0:02:00  0:27:37 8544k
  6 11.5G    6  815M    0     0  6854k      0  0:29:31  0:02:01  0:27:30 8652k
  6 11.5G    6  824M    0     0  6868k      0  0:29:28  0:02:02  0:27:26 8804k
  7 11.5G    7  832M    0     0  6879k      0  0:29:25  0:02:03  0:27:22 8816k
  7 11.5G    7  838M    0     0  6881k      0  0:29:24  0:02:04  0:27:20 8526k
  7 11.5G    7  847M    0     0  6894k      0  0:29:21  0:02:05  0:27:16 8422k
  7 11.5G    7  855M    0     0  6899k      0  0:29:20  0:02:06  0:27:14 7979k
  7 11.5G    7  863M    0     0  6914k      0  0:29:16  0:02:07  0:27:09 8035k
  7 11.5G    7  871M    0     0  6926k      0  0:29:13  0:02:08  0:27:05 8098k
  7 11.5G    7  879M    0     0  6933k      0  0:29:11  0:02:09  0:27:02 8249k
  7 11.5G    7  888M    0     0  6952k      0  0:29:06  0:02:10  0:26:56 8431k
  7 11.5G    7  896M    0     0  6966k      0  0:29:03  0:02:11  0:26:52 8679k
  7 11.5G    7  905M    0     0  6974k      0  0:29:01  0:02:12  0:26:49 8519k
  7 11.5G    7  911M    0     0  6929k      0  0:29:12  0:02:14  0:26:58 7013k
  7 11.5G    7  911M    0     0  6916k      0  0:29:15  0:02:14  0:27:01 6473k
  7 11.5G    7  913M    0     0  6881k      0  0:29:24  0:02:15  0:27:09 5024k
  7 11.5G    7  913M    0     0  6827k      0  0:29:38  0:02:17  0:27:21 3318k
  7 11.5G    7  918M    0     0  6822k      0  0:29:39  0:02:17  0:27:22 2775k
  7 11.5G    7  923M    0     0  6807k      0  0:29:43  0:02:18  0:27:25 2835k
  7 11.5G    7  927M    0     0  6794k      0  0:29:47  0:02:19  0:27:28 3414k
  7 11.5G    7  932M    0     0  6782k      0  0:29:50  0:02:20  0:27:30 4082k
  7 11.5G    7  938M    0     0  6771k      0  0:29:53  0:02:21  0:27:32 5179k
  7 11.5G    7  943M    0     0  6760k      0  0:29:56  0:02:22  0:27:34 5029k
  8 11.5G    8  948M    0     0  6753k      0  0:29:58  0:02:23  0:27:35 5261k
  8 11.5G    8  953M    0     0  6741k      0  0:30:01  0:02:24  0:27:37 5283k
  8 11.5G    8  959M    0     0  6733k      0  0:30:03  0:02:25  0:27:38 5348k
  8 11.5G    8  964M    0     0  6724k      0  0:30:05  0:02:26  0:27:39 5372k
  8 11.5G    8  968M    0     0  6707k      0  0:30:10  0:02:27  0:27:43 5219k
  8 11.5G    8  973M    0     0  6699k      0  0:30:12  0:02:28  0:27:44 5146k
  8 11.5G    8  977M    0     0  6681k      0  0:30:17  0:02:29  0:27:48 4938k
  8 11.5G    8  983M    0     0  6674k      0  0:30:19  0:02:30  0:27:49 4952k
  8 11.5G    8  988M    0     0  6667k      0  0:30:21  0:02:31  0:27:50 4998k
  8 11.5G    8  994M    0     0  6665k      0  0:30:21  0:02:32  0:27:49 5406k
  8 11.5G    8 1001M    0     0  6663k      0  0:30:22  0:02:33  0:27:49 5583k
  8 11.5G    8 1007M    0     0  6658k      0  0:30:23  0:02:34  0:27:49 5964k
  8 11.5G    8 1013M    0     0  6658k      0  0:30:23  0:02:35  0:27:48 6185k
  8 11.5G    8 1021M    0     0  6667k      0  0:30:21  0:02:36  0:27:45 6665k
  8 11.5G    8 1024M    0     0  6671k      0  0:30:20  0:02:37  0:27:43 6900k
curl: (18) transfer closed with 11361380843 bytes remaining to read"
Output: ""

**Comment by Ben216k** [comment]
Duplicate issue.
