### ISSUE TITLE
Can't active pCloud virtual drive ?

### ISSUE THREAD

**Issue by PierreEmmD** [Ben216k/Patched-Sur#46]
**Describe the bug**

Can't activate pCloud Drive in the finder since my mac updated to Big Sur with Patched Sur 1.0.1.

Driver problem ?

**Expected behavior**
Hello,

I have a problem to use pCloud on mac os x Big Sur after updated with Patched Sur.

I used pCloud drive in the finder to access my cloud folders.
I activated the pCloud drive (screenshot).
I autorized pCloud in System preferences -> Security and Confidentiality, but nothing append next, also after shutdown and restart my mac.

Does a driver in Patched Sur  unlocked virtual drive ?

Thanks.

**Screenshots**
https://filedn.eu/lIEFoyVxgMp5MNqzU28PBUy/Capture%20d%E2%80%99e%CC%81cran%202022-02-23%20a%CC%80%2010.14.17.png

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
 - Upgrading to: Big Sur v11.6.4
 - Mac Model: 15" mi-2012 MacBook Pro
 - Version 1.0.1 (122)

**Additional context**
None.

If there are any red boxes, click on them to copy the logs.

**Comment by Ben216k** [comment]
(Sorry for the late response, I have not really been taking care of this project due to the soon EOL of it)

I'd say this lands on pCloud rather than the patcher, nothing in the patcher affects virtual drives and this is the only mention I've had of it so far.
