### ISSUE TITLE
Update to 11.6.5 and Patched Sur 1.1.0 (124) no Lan

### ISSUE THREAD

**Issue by mahoessen** [Ben216k/Patched-Sur#48]
**Describe the bug**
i was running on osx 11.6.4. and patched Sur 1.0.1.

after updating to patched Sur 1.1.0,  and updating to osx 11.6.5 the is no Lan connection possible and no Audio.
Wlan is running without problems.

I use the kexts patches via the Patched Sur app, offline after creating and booting from a new installer and using the patched system.sh and the patchkexts.sh
the machine is a iMac Mid2011 27", imac12,2 with metal graphic card "Quadro K1000M by Nick[D]vB 2 GB"

everything else is running fast and fine

thanks for an info how to get the lan connection running

mahoessen
![Bildschirmfoto 2022-03-17 um 08 24 41](https://user-images.githubusercontent.com/101790562/158757800-6e18ac44-0063-4826-9e7e-19d6a494e2f5.png)
n

**Comment by Ben216k** [comment]
Pre-2012 Macs are not (and never have been) supported by this patcher. Use OCLP instead.
