### ISSUE TITLE
error with installation

### ISSUE THREAD

**Issue by MechanicAri** [Ben216k/Patched-Sur#49]
Error 1x251
Message: "Erasing disk: 0%... 10%... 20%... 30%... 100%
Error: Error Domain=NSCocoaErrorDomain Code=512 "“License.rtf” couldn’t be copied to “uk.lproj”." UserInfo={NSSourceFilePathErrorKey=/Applications/Install macOS Big Sur.app/Contents/Resources/uk.lproj/License.rtf, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Volumes/Install macOS Big Sur/Install macOS Big Sur.app/Contents/Resources/uk.lproj/License.rtf, NSFilePath=/Applications/Install macOS Big Sur.app/Contents/Resources/uk.lproj/License.rtf, NSUnderlyingError=0x7ff621723550 {Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument"}}The copy of the installer app failed."
Output: "Copying to disk: 0%..."

can anyone help?

**Comment by Ben216k** [comment]
This is on Apple, they made the program for any user to use (it's not modified specially to use in a patcher), and it has bugs, which is why it doesn't always work in Patched Sur. All I can recommend is trying again.
