### ISSUE TITLE
Computer wont Connect to Hidden Wifi Network

### ISSUE THREAD

**Issue by Dragon951** [Ben216k/Patched-Sur#5]
**Describe the bug**
im trying to connect to a hidden wifi network but will not let me connect

im on big sur 11.6 with macbook pro mid 2012

**To Reproduce**
try to connect to a hidden network and you will see it wont work

**Expected behavior**
for the computer to connect to the hidden network like how it did with OS Catalina and others

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7]
- Upgrading to: 11.6 (big Sur)
 - Mac Model: [13" 2012 MacBook Pro]
 - Version [e.g. v1.0.1]

**Comment by TheFaon** [comment]
I have the same problem

**Comment by Ben216k** [comment]
Before you guys make a chain of "I have the same problem", note that this is a known bug that can be reproduced on Patched Sur devices (expect Late-2013 iMacs).

**Comment by TheFaon** [comment]
> Before you guys make a chain of "I have the same problem", note that this is a known bug that can be reproduced on Patched Sur devices (expect Late-2013 iMacs). I already know that you have the same problem.

Sorry but what I'm supposed to do ?

**Comment by Ben216k** [comment]
You can't do anything, I'm just telling people not to make a chain of "Same here" since I already know that everyone's Mac is affected (that happened before, it got annoying).

**Comment by TheFaon** [comment]
> You can't do anything, I'm just telling people not to make a chain of "Same here" since I already know that everyone's Mac is affected (that happened before, it got annoying).

Okay so how can I get back on Catalina ?

**Comment by nictse2013** [comment]
U can open boardcast,connect wifi then close boardcast.
DO NOT close wifi.
if u do it,u need do above all over again.

**Comment by Ben216k** [comment]
Have you guys tried v1.1.0? I use a new Wi-Fi patch now (see native-something instead of Mojave-hybrid in Advanced Patches), and it's solved many existing Wi-Fi problems. If you're still having this issue (or still even interested in this patcher haha), then that should help.

**Comment by froilainhaeckse** [comment]
Hey @Ben216k , I just wanted to let you know that it worked for me! Thank you very much. I would see the issue as resolved!

Steps to reproduce:
- Updated Mid 2012 Mac Book Air to Big Sur with patched OS
- WIFI did not work at all
- Used the Post-Install Patch and followed the described Steps (Unpatch Kexts) and WIFI works again :) 

Thank you very much!!!

**Comment by Ben216k** [comment]
Awesome! I'll mark it as fixed then
