### ISSUE TITLE
Error 1x18

### ISSUE THREAD

**Issue by pedrosabinofilho** [Ben216k/Patched-Sur#50]
Error 1x18
Message: "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 11.5G    0 1454k    0     0  3351k      0  1:00:17 --:--:--  1:00:17 3343k
  0 11.5G    0 5388k    0     0  3749k      0  0:53:52  0:00:01  0:53:51 3747k
  0 11.5G    0 9498k    0     0  3895k      0  0:51:51  0:00:02  0:51:49 3894k
  0 11.5G    0 12.9M    0     0  3867k      0  0:52:14  0:00:03  0:52:11 3866k
  0 11.5G    0 16.7M    0     0  3858k      0  0:52:21  0:00:04  0:52:17 3858k
  0 11.5G    0 21.3M    0     0  4027k      0  0:50:09  0:00:05  0:50:04 4086k
  0 11.5G    0 25.4M    0     0  4046k      0  0:49:55  0:00:06  0:49:49 4130k
  0 11.5G    0 29.1M    0     0  4010k      0  0:50:22  0:00:07  0:50:15 4064k
  0 11.5G    0 32.7M    0     0  3973k      0  0:50:50  0:00:08  0:50:42 4045k
  0 11.5G    0 36.3M    0     0  3940k      0  0:51:16  0:00:09  0:51:07 4012k
  0 11.5G    0 40.3M    0     0  3958k      0  0:51:02  0:00:10  0:50:52 3882k
  0 11.5G    0 44.7M    0     0  4004k      0  0:50:27  0:00:11  0:50:16 3951k
  0 11.5G    0 48.0M    0     0  3953k      0  0:51:06  0:00:12  0:50:54 3868k
  0 11.5G    0 52.5M    0     0  4001k      0  0:50:28  0:00:13  0:50:15 4049k
  0 11.5G    0 56.7M    0     0  4024k      0  0:50:12  0:00:14  0:49:58 4183k
  0 11.5G    0 61.3M    0     0  4071k      0  0:49:37  0:00:15  0:49:22 4308k
  0 11.5G    0 65.9M    0     0  4112k      0  0:49:07  0:00:16  0:48:51 4357k
  0 11.5G    0 71.3M    0     0  4193k      0  0:48:10  0:00:17  0:47:53 4790k
  0 11.5G    0 77.2M    0     0  4290k      0  0:47:05  0:00:18  0:46:47 5065k
  0 11.5G    0 80.8M    0     0  4260k      0  0:47:24  0:00:19  0:47:05 4943k
  0 11.5G    0 84.9M    0     0  4256k      0  0:47:27  0:00:20  0:47:07 4828k
  0 11.5G    0 88.7M    0     0  4241k      0  0:47:37  0:00:21  0:47:16 4666k
  0 11.5G    0 92.6M    0     0  4230k      0  0:47:45  0:00:22  0:47:23 4359k
  0 11.5G    0 97.0M    0     0  4242k      0  0:47:37  0:00:23  0:47:14 4065k
  0 11.5G    0  101M    0     0  4245k      0  0:47:34  0:00:24  0:47:10 4188k
  0 11.5G    0  106M    0     0  4284k      0  0:47:09  0:00:25  0:46:44 4395k
  0 11.5G    0  111M    0     0  4303k      0  0:46:56  0:00:26  0:46:30 4572k
  0 11.5G    0  115M    0     0  4296k      0  0:47:01  0:00:27  0:46:34 4592k
  1 11.5G    1  119M    0     0  4290k      0  0:47:05  0:00:28  0:46:37 4514k
  1 11.5G    1  123M    0     0  4301k      0  0:46:58  0:00:29  0:46:29 4570k
  1 11.5G    1  126M    0     0  4269k      0  0:47:19  0:00:30  0:46:49 4192k
  1 11.5G    1  130M    0     0  4254k      0  0:47:29  0:00:31  0:46:58 3993k
  1 11.5G    1  133M    0     0  4228k      0  0:47:46  0:00:32  0:47:14 3853k
  1 11.5G    1  137M    0     0  4204k      0  0:48:03  0:00:33  0:47:30 3716k
  1 11.5G    1  141M    0     0  4205k      0  0:48:02  0:00:34  0:47:28 3642k
  1 11.5G    1  145M    0     0  4213k      0  0:47:56  0:00:35  0:47:21 3873k
  1 11.5G    1  149M    0     0  4204k      0  0:48:03  0:00:36  0:47:27 3888k
  1 11.5G    1  154M    0     0  4232k      0  0:47:44  0:00:37  0:47:07 4256k
  1 11.5G    1  158M    0     0  4216k      0  0:47:54  0:00:38  0:47:16 4300k
  1 11.5G    1  162M    0     0  4208k      0  0:48:00  0:00:39  0:47:21 4231k
  1 11.5G    1  165M    0     0  4192k      0  0:48:11  0:00:40  0:47:31 4046k
  1 11.5G    1  169M    0     0  4186k      0  0:48:15  0:00:41  0:47:34 4060k
  1 11.5G    1  173M    0     0  4181k      0  0:48:19  0:00:42  0:47:37 3800k
  1 11.5G    1  178M    0     0  4201k      0  0:48:05  0:00:43  0:47:22 4080k
  1 11.5G    1  182M    0     0  4203k      0  0:48:03  0:00:44  0:47:19 4164k
  1 11.5G    1  185M    0     0  4183k      0  0:48:17  0:00:45  0:47:32 4111k
  1 11.5G    1  188M    0     0  4166k      0  0:48:28  0:00:46  0:47:42 4000k
  1 11.5G    1  192M    0     0  4145k      0  0:48:43  0:00:47  0:47:56 3845k
  1 11.5G    1  195M    0     0  4135k      0  0:48:51  0:00:48  0:48:03 3561k
  1 11.5G    1  198M    0     0  4121k      0  0:49:00  0:00:49  0:48:11 3392k
  1 11.5G    1  202M    0     0  4117k      0  0:49:04  0:00:50  0:48:14 3511k
  1 11.5G    1  206M    0     0  4115k      0  0:49:05  0:00:51  0:48:14 3641k
  1 11.5G    1  210M    0     0  4117k      0  0:49:03  0:00:52  0:48:11 3847k
  1 11.5G    1  216M    0     0  4149k      0  0:48:41  0:00:53  0:47:48 4283k
  1 11.5G    1  220M    0     0  4143k      0  0:48:45  0:00:54  0:47:51 4363k
  1 11.5G    1  224M    0     0  4150k      0  0:48:40  0:00:55  0:47:45 4490k
  1 11.5G    1  228M    0     0  4150k      0  0:48:40  0:00:56  0:47:44 4512k
  1 11.5G    1  232M    0     0  4147k      0  0:48:42  0:00:57  0:47:45 4467k
  1 11.5G    1  236M    0     0  4143k      0  0:48:45  0:00:58  0:47:47 4087k
  2 11.5G    2  240M    0     0  4137k      0  0:48:49  0:00:59  0:47:50 4071k
  2 11.5G    2  243M    0     0  4133k      0  0:48:52  0:01:00  0:47:52 3939k
  2 11.5G    2  248M    0     0  4146k      0  0:48:43  0:01:01  0:47:42 4093k
  2 11.5G    2  253M    0     0  4149k      0  0:48:40  0:01:02  0:47:38 4173k
  2 11.5G    2  257M    0     0  4150k      0  0:48:40  0:01:03  0:47:37 4230k
  2 11.5G    2  261M    0     0  4158k      0  0:48:34  0:01:04  0:47:30 4402k
  2 11.5G    2  265M    0     0  4160k      0  0:48:33  0:01:05  0:47:28 4488k
  2 11.5G    2  269M    0     0  4157k      0  0:48:35  0:01:06  0:47:29 4298k
  2 11.5G    2  272M    0     0  4143k      0  0:48:45  0:01:07  0:47:38 4065k
  2 11.5G    2  277M    0     0  4146k      0  0:48:43  0:01:08  0:47:35 4090k
  2 11.5G    2  281M    0     0  4152k      0  0:48:39  0:01:09  0:47:30 4072k
  2 11.5G    2  286M    0     0  4161k      0  0:48:32  0:01:10  0:47:22 4177k
  2 11.5G    2  291M    0     0  4173k      0  0:48:24  0:01:11  0:47:13 4387k
  2 11.5G    2  295M    0     0  4176k      0  0:48:21  0:01:12  0:47:09 4626k
  2 11.5G    2  299M    0     0  4181k      0  0:48:18  0:01:13  0:47:05 4662k
  2 11.5G    2  302M    0     0  4166k      0  0:48:29  0:01:14  0:47:15 4365k
  2 11.5G    2  306M    0     0  4158k      0  0:48:35  0:01:15  0:47:20 4107k
  2 11.5G    2  310M    0     0  4158k      0  0:48:34  0:01:16  0:47:18 3940k
  2 11.5G    2  315M    0     0  4174k      0  0:48:23  0:01:17  0:47:06 4135k
  2 11.5G    2  319M    0     0  4170k      0  0:48:26  0:01:18  0:47:08 4008k
  2 11.5G    2  324M    0     0  4177k      0  0:48:21  0:01:19  0:47:02 4348k
  2 11.5G    2  328M    0     0  4180k      0  0:48:19  0:01:20  0:46:59 4520k
  2 11.5G    2  332M    0     0  4183k      0  0:48:17  0:01:21  0:46:56 4557k
  2 11.5G    2  336M    0     0  4184k      0  0:48:16  0:01:22  0:46:54 4346k
  2 11.5G    2  339M    0     0  4170k      0  0:48:26  0:01:23  0:47:03 4179k
  2 11.5G    2  344M    0     0  4183k      0  0:48:17  0:01:24  0:46:53 4272k
  2 11.5G    2  350M    0     0  4195k      0  0:48:08  0:01:25  0:46:43 4440k
  2 11.5G    2  354M    0     0  4198k      0  0:48:07  0:01:26  0:46:41 4446k
  3 11.5G    3  358M    0     0  4201k      0  0:48:05  0:01:27  0:46:38 4471k
  3 11.5G    3  362M    0     0  4200k      0  0:48:05  0:01:28  0:46:37 4689k
  3 11.5G    3  366M    0     0  4195k      0  0:48:08  0:01:29  0:46:39 4403k
  3 11.5G    3  370M    0     0  4191k      0  0:48:12  0:01:30  0:46:42 4113k
  3 11.5G    3  373M    0     0  4179k      0  0:48:20  0:01:31  0:46:49 3850k
  3 11.5G    3  377M    0     0  4180k      0  0:48:19  0:01:32  0:46:47 3824k
  3 11.5G    3  381M    0     0  4178k      0  0:48:20  0:01:33  0:46:47 3793k
  3 11.5G    3  384M    0     0  4174k      0  0:48:23  0:01:34  0:46:49 3791k
  3 11.5G    3  389M    0     0  4181k      0  0:48:18  0:01:35  0:46:43 4003k
  3 11.5G    3  393M    0     0  4175k      0  0:48:23  0:01:36  0:46:47 4100k
  3 11.5G    3  396M    0     0  4169k      0  0:48:27  0:01:37  0:46:50 3958k
  3 11.5G    3  400M    0     0  4165k      0  0:48:30  0:01:38  0:46:52 3917k
  3 11.5G    3  405M    0     0  4179k      0  0:48:20  0:01:39  0:46:41 4279k
  3 11.5G    3  409M    0     0  4171k      0  0:48:26  0:01:40  0:46:46 3974k
  3 11.5G    3  412M    0     0  4164k      0  0:48:30  0:01:41  0:46:49 3959k
  3 11.5G    3  416M    0     0  4161k      0  0:48:32  0:01:42  0:46:50 4001k
  3 11.5G    3  420M    0     0  4160k      0  0:48:33  0:01:43  0:46:50 4068k
  3 11.5G    3  424M    0     0  4157k      0  0:48:35  0:01:44  0:46:51 3726k
  3 11.5G    3  428M    0     0  4166k      0  0:48:29  0:01:45  0:46:44 4072k
  3 11.5G    3  434M    0     0  4176k      0  0:48:21  0:01:46  0:46:35 4426k
  3 11.5G    3  439M    0     0  4188k      0  0:48:14  0:01:47  0:46:27 4742k
  3 11.5G    3  443M    0     0  4189k      0  0:48:13  0:01:48  0:46:25 4781k
  3 11.5G    3  447M    0     0  4185k      0  0:48:16  0:01:49  0:46:27 4753k
  3 11.5G    3  451M    0     0  4184k      0  0:48:16  0:01:50  0:46:26 4560k
  3 11.5G    3  456M    0     0  4196k      0  0:48:08  0:01:51  0:46:17 4605k
  3 11.5G    3  460M    0     0  4191k      0  0:48:11  0:01:52  0:46:19 4260k
  3 11.5G    3  465M    0     0  4205k      0  0:48:02  0:01:53  0:46:09 4550k
  3 11.5G    3  471M    0     0  4216k      0  0:47:54  0:01:54  0:46:00 4903k
  4 11.5G    4  475M    0     0  4215k      0  0:47:55  0:01:55  0:46:00 4912k
  4 11.5G    4  480M    0     0  4226k      0  0:47:48  0:01:56  0:45:52 4899k
  4 11.5G    4  484M    0     0  4223k      0  0:47:50  0:01:57  0:45:53 4934k
  4 11.5G    4  488M    0     0  4222k      0  0:47:50  0:01:58  0:45:52 4626k
  4 11.5G    4  493M    0     0  4228k      0  0:47:46  0:01:59  0:45:47 4493k
  4 11.5G    4  497M    0     0  4231k      0  0:47:44  0:02:00  0:45:44 4589k
  4 11.5G    4  501M    0     0  4228k      0  0:47:46  0:02:01  0:45:45 4267k
  4 11.5G    4  505M    0     0  4229k      0  0:47:46  0:02:02  0:45:44 4370k
  4 11.5G    4  508M    0     0  4220k      0  0:47:51  0:02:03  0:45:48 4169k
  4 11.5G    4  512M    0     0  4220k      0  0:47:51  0:02:04  0:45:47 4042k
  4 11.5G    4  516M    0     0  4214k      0  0:47:55  0:02:05  0:45:50 3817k
  4 11.5G    4  520M    0     0  4214k      0  0:47:56  0:02:06  0:45:50 3880k
  4 11.5G    4  523M    0     0  4210k      0  0:47:59  0:02:07  0:45:52 3741k
  4 11.5G    4  528M    0     0  4214k      0  0:47:56  0:02:08  0:45:48 4057k
  4 11.5G    4  532M    0     0  4216k      0  0:47:55  0:02:09  0:45:46 4102k
  4 11.5G    4  537M    0     0  4217k      0  0:47:53  0:02:10  0:45:43 4292k
  4 11.5G    4  541M    0     0  4216k      0  0:47:54  0:02:11  0:45:43 4264k
  4 11.5G    4  545M    0     0  4218k      0  0:47:53  0:02:12  0:45:41 4434k
  4 11.5G    4  549M    0     0  4214k      0  0:47:56  0:02:13  0:45:43 4216k
  4 11.5G    4  553M    0     0  4215k      0  0:47:55  0:02:14  0:45:41 4208k
  4 11.5G    4  557M    0     0  4214k      0  0:47:56  0:02:15  0:45:41 4128k
  4 11.5G    4  560M    0     0  4208k      0  0:47:59  0:02:16  0:45:43 4016k
  4 11.5G    4  564M    0     0  4206k      0  0:48:01  0:02:17  0:45:44 3898k
  4 11.5G    4  569M    0     0  4215k      0  0:47:55  0:02:18  0:45:37 4247k
  4 11.5G    4  573M    0     0  4210k      0  0:47:59  0:02:19  0:45:40 4055k
  4 11.5G    4  577M    0     0  4208k      0  0:47:59  0:02:20  0:45:39 4051k
  4 11.5G    4  580M    0     0  4202k      0  0:48:04  0:02:21  0:45:43 4015k
  4 11.5G    4  583M    0     0  4198k      0  0:48:07  0:02:22  0:45:45 3957k
  4 11.5G    4  587M    0     0  4191k      0  0:48:11  0:02:23  0:45:48 3536k
  4 11.5G    4  591M    0     0  4190k      0  0:48:12  0:02:24  0:45:48 3649k
  5 11.5G    5  594M    0     0  4185k      0  0:48:15  0:02:25  0:45:50 3543k
  5 11.5G    5  599M    0     0  4194k      0  0:48:10  0:02:26  0:45:44 3969k
  5 11.5G    5  603M    0     0  4191k      0  0:48:11  0:02:27  0:45:44 4011k
  5 11.5G    5  607M    0     0  4188k      0  0:48:13  0:02:28  0:45:45 4096k
  5 11.5G    5  610M    0     0  4185k      0  0:48:16  0:02:29  0:45:47 4036k
  5 11.5G    5  613M    0     0  4175k      0  0:48:22  0:02:30  0:45:52 3885k
  5 11.5G    5  617M    0     0  4174k      0  0:48:23  0:02:31  0:45:52 3591k
  5 11.5G    5  622M    0     0  4179k      0  0:48:20  0:02:32  0:45:48 3823k
  5 11.5G    5  626M    0     0  4184k      0  0:48:16  0:02:33  0:45:43 4057k
  5 11.5G    5  630M    0     0  4183k      0  0:48:17  0:02:34  0:45:43 4121k
  5 11.5G    5  634M    0     0  4181k      0  0:48:18  0:02:35  0:45:43 4343k
  5 11.5G    5  639M    0     0  4186k      0  0:48:15  0:02:36  0:45:39 4568k
  5 11.5G    5  642M    0     0  4184k      0  0:48:16  0:02:37  0:45:39 4325k
curl: (18) transfer closed with 11738471476 bytes remaining to read"
Output: ""

Can anybody help?

**Comment by Blueysh** [comment]
Refer to the bottom of #47 for a solution, a lot of people have this issue.

**Comment by Ben216k** [comment]
Duplicate issue
