### ISSUE TITLE
No support Mac Mini 2012 i7

### ISSUE THREAD

**Issue by SergioXII12** [Ben216k/Patched-Sur#52]
No support on Mac Mini 2012 i7 model  MD389LL/A using latest version.

The mac is equipped with 500 GB SSD Samsung 850 EVO and 16 GB RAM with Catalina installed.

The patch simply returns message "No Support".

![IMG_1710](https://user-images.githubusercontent.com/76035479/163765813-1b972a23-5542-4b2c-a66a-fac8c861bdb9.JPG)

**Comment by Ben216k** [comment]
All Russian translations have been removed and replaced with the "NO SUPPORT" message you see, it's the language not the Mac. The patcher still works, I didn't go through that much effort, just a simple find and replace in the translation file.
