### ISSUE TITLE
Error 1x6

### ISSUE THREAD

**Issue by thomasklaush** [Ben216k/Patched-Sur#54]
iMac (27-inch, Late 2013)
Running on external SSD
Patched Sur 1.1.0 (124)

I want to update from 11.6.2 patched Sur to 11.6.5

Every time after the download I get the same error.

Error 1x6
Message: "dyld: could not load inserted library '/usr/local/lib/Patched-Sur-Patches/InstallerHax/Hax6/Hax6.dylib' because image not found
"
Output: ""

**Comment by Ben216k** [comment]
You have to restart between update attempts.
