### ISSUE TITLE
NO SUPPORT caption

### ISSUE THREAD

**Issue by Nordsoft91** [Ben216k/Patched-Sur#55]
**Describe the bug**
NO SUPPORT caption when application is started

**To Reproduce**
1. Download [Patched-Sur.dmg](https://github.com/Ben216k/Patched-Sur/releases/download/v1.1.0/Patched-Sur.dmg) from Releases page Patched Sur v1.1.0
2. Open Patched-Sur.dmg
3. Open Patched Sur

**Expected behavior**
Normal behaviour

**Screenshots**
<img width="576" alt="Снимок экрана 2022-05-15 в 14 57 26" src="https://user-images.githubusercontent.com/9308612/168471569-f0e7e77a-ec97-48b2-b8ae-8113fd8eb58c.png">

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: N/A
 - Mac Model: MacBook Pro (Retina, Mid 2012)
 - Version v1.1.0

**Comment by Ben216k** [comment]
Russian support was removed

**Comment by xaiamov** [comment]
Why doesn't it show English instead?
