### ISSUE TITLE
Cant download audio interface dmg..says it won't save to the library folder....?

### ISSUE THREAD

**Issue by sderienzo** [Ben216k/Patched-Sur#58]
**Describe the bug**
I am trying to download an audio interface app from the manufactures website. The website is this https://downloads.focusrite.com/focusrite/scarlett-3rd-gen/scarlett-18i8-3rd-gen

The app download seems to be fine until you try to open the app and then it crashes and sends a message to terminal which I have included in this. I just upgraded to the patcher yesterday so I could legally download Logic X. 

**To Reproduce**
1. Go to the website listed above
2. Click on 'what ever mac download you want
3. try to open the app after it installs

**Expected behavior**
When I try to open the focusrite app it crashes before it opens.. it says there was an error with permissions on with the "client" folder. 

**Screenshots**
![Screen Shot 2022-07-12 at 11 37 41 AM](https://user-images.githubusercontent.com/12439532/178569767-0fee0342-b14a-41dc-8503-d380c54c8240.png)

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [ Big Sur v11.6.7 ]
 - Mac Model: [ 15" mid 2012 MacBook Pro]
 - Version [e.g. v0.0.4]

**Additional context**

If there are any red boxes, click on them to copy the logs.

**Comment by Ben216k** [comment]
That's an app permission error, which has nothing to do with the patcher. The problem is with the app itself.
