### ISSUE TITLE
macOS Big Sur 11.7 not available

### ISSUE THREAD

**Issue by Atten007** [Ben216k/Patched-Sur#60]
**Describe the bug**
Hi folks,

We‘ve a Mac mini 2011 at home and we want to install macOS Big Sur with graphics acceleration there with this app. But unfortunately, the newest macOS Big Sur Version 11.7 isn’t available yet. @ben216k is it possible to update the patcher to macOS Big Sur 11.7?

**To Reproduce**
Unfortunately, there‘s nothing to reproduce because only the newest macOS Big Sur Version is missing

**Expected behavior**
macOS Big Sur 11.7 should be available.

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: macOS High Sierra 10.13.6
 - Upgrading to: macOS Big Sur 11.7
 - Mac Model: Mac Mini Mid 2011
 - Version 1.1.0

**Additional context**
Nothing additional to say.

**Comment by Ben216k** [comment]
Oops
