### ISSUE TITLE
Download update issue

### ISSUE THREAD

**Issue by Jakethewhite** [Ben216k/Patched-Sur#62]
I would give a screenshot but it's a black screen, I updated the latest update on my MacBook pro 2012 and it now doesn't start and just gives me three beeps. If I can get the screen to turn on every 20th start up it comes to the login screen and freezes the screen with glitch lines all over and then reverts back to a black screen with three beeps. I can't use my computer or turn on in safe mode after this update.

**Comment by Ben216k** [comment]
That means there's an actual problem with your Mac, not anything related to Patched Sur. (Quick google search says RAM or firmware, neither of which Patched Sur touches)
