### ISSUE TITLE
Sound don't work

### ISSUE THREAD

**Issue by AurelioGrande** [Ben216k/Patched-Sur#63]
After update my macbook pro 2011 with Big Sur patch my sound don't work anymore. 
![Captura de Tela 2022-11-10 às 18 58 29](https://user-images.githubusercontent.com/118024297/201435166-865afa7c-aac5-4aad-8569-08e814568f66.png)

**Comment by Ben216k** [comment]
Not only is Patched Sur losing support, but it never supported 2011 Macs to begin with. I'm 99% sure I ever added something that blocked you from upgrading on 2011 Macs.
