### ISSUE TITLE
Unable to Update Without Required NVRAM Value

### ISSUE THREAD

**Issue by Kamelc53** [Ben216k/Patched-Sur#9]
I am on macOS Big Sur version 11.5 (Macbook Pro Mid-2012) don't know if I can update to version 11.6, because of NVRAM Value which is missing. I am getting a red banner on Patch Sur saying Required NVRAM VALUE is missing
also, I've tried both instructions; Restoring the missing value with the USB installer booting to the purple EFI boot drive as well as with Internet recovery 
I would be grateful if you can help me out with this issue @Ben216k  thanks in advance.  
![Screen Shot 2021-10-27 at 18 14 24](https://user-images.githubusercontent.com/90094158/139114432-6d30e16c-d4fa-40b1-ba09-00fa12d9289f.png)

**Comment by Ben216k** [comment]
Updating without OC? Just use Patched Sur.

Updating with OC? Just use the Software Update pane in System Preferences.

**Comment by Roderick8472** [comment]
Thank you so much for your reply. I appreciate your help.

**Comment by Hk92a** [comment]
Duplicate of #
